### ISSUE TITLE
Default color scheme recommendation, move from danger-zone into info-zone

### ISSUE THREAD

**Issue by the-black-wolf** [controlflow/resharper-heapview#122]
For me, at least, red = “danger, pay attention”. And most of the Rider hints are just fine, showing as green dots below. However, for some reason HeapView.ObjectAllocation chooses to show up as a red underline

![image](https://github.com/controlflow/resharper-heapview/assets/15175507/7511f5a2-3362-4e2c-8827-42aeb7078a73)

Honestly, very noisy and attention grabbing, especially for unavoidable situations such as string interpolation or by marking all new operators.

As you said yourself, "dont over optimize, only when needed", and I don't really need o have new operator highlighted, etc. This type of analysis should be on-demand. 

In the Rider light theme, the Hints are shown as green dots. Why not make these Hints informational (blue, green, etc) by default and not in danger-zone (yellow red etc).

**Comment by controlflow** [comment]
I guess you probably mention boxing underline being red (underline in screenshot is yellow, `HeapView.ObjectAllocation` inspection).

I'm not sure why exactly you get this "attention grabbing"/"danger zone"/"very noisy" feeling from just red/yellow colors :) Back in the 2014 days this plugin was used to help writing allocationless code where unnecessary boxing can be classified as a "danger", so I picked red color. Nobody ever complained about it since then :) For ordinary allocations I picked less attracting yellow color.

I think I'll change the colors to "info-zone", probably you're right :)You can change those colors in your IDE via
