### ISSUE TITLE
Resharper 2017.3

### ISSUE THREAD

**Issue by DmitriyYukhanov** [controlflow/resharper-heapview#54]
Hey there!
This plugin is a must have and sadly it was not updated for 2017.3 ReSharper, would be nice to see an update!

**Comment by kevingosse** [comment]
I've forked the plugin to update it for 2017.2, since this one doesn't seem to be active anymore (see https://github.com/controlflow/resharper-heapview/issues/50). Unfortunately, I'm having some issues with 2017.3, hints are not displayed properly and I haven't managed to find out why. I filled a bug to jetbrains, voting on it can help: https://youtrack.jetbrains.com/issue/RSRP-467708

I'll publish the version for 2017.3 as soon as the bug is fixed. Fork is there, any help is welcome: https://github.com/kevingosse/resharper-heapview

**Comment by DmitriyYukhanov** [comment]
Thanks for making a fork for newer ReSharper versions, @kevingosse 
You have few votes from me and my colleagues on that issue.

I also noticed Matt Ellis from JetBrains (@citizenmatt) has a fork for Rider with ReSharper 2017.2 and Rider support (https://github.com/citizenmatt/resharper-heapview/commits/feature/rider), it could be worth trying to contact him and ask about further plans on the plugin maintenance and updates for Resharper to avoid making double work.

**Comment by citizenmatt** [comment]
I've just pushed a new version to the gallery that adds ReSharper 2017.3 support. Should be available in ReSharper &rarr; Extension Manager.

**Comment by kevingosse** [comment]
For some reason you didn't run into the same annotation bug as I did. Weird, I wonder where I messed up.

Thanks for the packaging :)

**Comment by citizenmatt** [comment]
Oh sorry, I hadn't read the comments properly, and didn't realise you were also working on a fork. I just carried on my PR from 2017.2 and Rider (and I'd got pinged internally for a Rider 2017.3 build).

The bug you're encountering is, of course, by design :) It's a change of policy for ReSharper 2017.3 - the installer now applies [zone filtering](https://www.jetbrains.com/help/resharper/sdk/Platform/Zones.html) to Visual Studio MEF components. To be honest, I don't actually know the how and the why of this - I don't know why our component model has anything to do with MEF components, but in order to get things working, you need to make sure that the namespace that contains any `ClassificationFormatDefinition` based classes has a zone marker that requires the `IVisualStudioZone`. You can see it in action in the new [`VisualStudio` folder](https://github.com/citizenmatt/resharper-heapview/tree/117f4e101032c2cfe698303d8a0b7d8bd600294d/ReSharper.HeapView/src/VisualStudio) I created in my fork.

**Comment by citizenmatt** [comment]
A little more information - it's because the installer needs to generate Visual Studio registration information, and we have several assemblies that target different versions of Visual Studio. If we blindly add all assemblies, we get conflicting duplicates, so we have to filter based on versions. We already have a mechanism for that - zones.

But that also mean that creating a zone marker with `IRequire<IVisualStudioZone>` isn't really enough, we also need to say what (minimum) version of Visual Studio we support. So I should technically be using `IRequire<ISinceVs10Zone>`.

**Comment by horaciojcfilho** [comment]
Hello @citizenmatt,

I am not seeing an updated version available to download for Rider 2017.3, please, could you check? I am using Rider 2017.3 and love this plugin :)

Thanks in advance!

**Comment by citizenmatt** [comment]
No, the Rider version isn't available to download yet. There's an issue with displaying the highlights (surprisingly similar in symptoms to the problem with VS described above, but actually completely separate). The dev team were looking into it, but I haven't heard anything, so I'll follow up.

**Comment by horaciojcfilho** [comment]
@citizenmatt Thank you very much :D Very appreciated the fast reply.

**Comment by citizenmatt** [comment]
BTW, Rider 2017.3 support is now available.
